name: Maestro UI Tests

on:
  push:
    branches: [main, runner]
  pull_request:
    branches: [main]

jobs:
  mobile-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Timeout is important because emulators can sometimes hang

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      # 1. Enable hardware acceleration (KVM) for the emulator
      - name: Enable KVM group permissions
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # 2. Install Maestro CLI
      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      # 3. Run Android Emulator and Maestro Tests
      - name: Prepare Maestro Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          disable-animations: true
          # Specify the AVD name
          avd-name: test
          script: bash run_script.sh
      
      - name: Upload Video to Slack
        if: always() # Ensures the video is sent even if the tests failed
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: files.uploadV2
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel_id: "GSFHH2TCP"
            initial_comment: "📺 *Maestro Test Result*: ${{ job.status }}\n🌿 *Branch*: `${{ github.ref_name }}`"
            file: "recording.mp4"